/**
 * One shared visual vocabulary for the human-facing exports (Word + PDF), so the
 * two documents read as one family and echo the app's own identity: slate for
 * sections, sky for the focus text, emerald for the genre. The deliberate
 * contrast is between the QUESTION (muted gray label) and the ANSWER (near-black,
 * larger) so a low-digital-literacy reader can see at a glance what was asked
 * versus what the team said.
 *
 * Colors are stored as bare hex (no `#`), which is what the `docx` library wants;
 * `hash()` adds the `#` for pdfmake. Sizes are in points; `docx` takes half-points
 * so its renderer doubles them.
 */

export const COLORS = {
  slate: '1F2937', // section headings + title (matches PWA theme_color)
  sky: '0369A1', // subsection headings + focus text (app uses sky-700)
  emerald: '047857', // genre accent (app uses emerald-700)
  question: '6B7280', // the prompt: muted, recedes
  answer: '111827', // the response: near-black, the emphasis
  amber: 'D97706', // priority accent
  na: '9CA3AF', // not-applicable: muted italic
  footer: '9CA3AF',
  rule: 'E5E7EB', // hairlines + table borders
} as const

export const SIZES = {
  title: 22,
  subtitle: 13,
  meta: 9,
  section: 15,
  subsection: 12,
  question: 9.5,
  answer: 11.5,
  badge: 8.5,
  na: 10,
  footer: 8,
  tableHeader: 9,
  tableCell: 10,
} as const

/** '#'-prefixed hex for pdfmake. */
export function hash(hex: string): string {
  return `#${hex}`
}

/** Points to docx half-points. */
export function halfPt(points: number): number {
  return Math.round(points * 2)
}

export const PRIORITY_BADGE = '★ PRIORITY' // ★ PRIORITY
export const NA_LABEL = 'Marked not applicable'
export const REPORT_TITLE = 'Local Genres Research — Findings'
export const FOOTER_LABEL = 'Generated by Local Genres Research'
